#!/usr/bin/env node
// scripts/sync-version.mjs — keep src/shared/version.ts in sync with the
// package.json version, run by `npm run build` BEFORE tsc. A stale
// hand-maintained copy made /mesh broker and the peer version-skew
// detection lie after releases (0.5.3 shown while shipping 0.7.0);
// generating at build time removes the human-bump failure mode entirely.
//
// RELEASE ORDERING (matters): `npm version patch` bumps package.json but
// NOT this generated file — always run `npm run build` after bumping and
// commit the regenerated src/shared/version.ts WITH the version commit,
// otherwise the tagged tree carries a lying version (version-sync.test
// fails on it).
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const pkg = JSON.parse(readFileSync(path.join(root, "package.json"), "utf8"));
if (typeof pkg.version !== "string" || pkg.version === "") {
  console.error("sync-version: package.json has no version field");
  process.exit(1);
}
const target = path.join(root, "src", "shared", "version.ts");
const current = readFileSync(target, "utf8");
if (current.includes(`MESH_VERSION = "${pkg.version}"`)) {
  process.exit(0); // already in sync — no rewrite, no churn
}
const content = `// shared/version.ts — GENERATED by scripts/sync-version.mjs from
// package.json at build time (never edit by hand). /mesh broker and status
// snapshots report this value; a stale hand-maintained copy made the peer
// version-skew detection lie after releases.
export const MESH_VERSION = "${pkg.version}";
`;
writeFileSync(target, content);
console.log(`sync-version: MESH_VERSION = ${pkg.version}`);
